### PR TITLE
official_builds:update cancro and wayne

### PR DESCRIPTION
**Pull request by bin8001**

### CODE REVIEW

**Comment by Jprimero15** [comment]
Push to gerrit

**Comment by BobRocket** [comment]
good

**Comment by BobRocket** [comment]
@Jprimero15 Gerrit doesn't have this project.

**Comment by BobRocket** [comment]
@Jprimero15 says bin8001

**Comment by ishubhamsingh** [comment]
> @Jprimero15 Gerrit doesn't have this project.

Yup it was just a confusion.

**Pull request merged**
